from locators.login_locator import *
from locators.register_locator import *
from locators.gmail_locator import *
from locators.home_locator import *
from locators.search_locator import *
from locators.message_locator import *
from locators.profile_locator import *
from locators.sidebar_locator import *
from locators.modal_locator import *
from locators.admin_locator import *
from locators.admin_modal_locator import *
