class AdminModalLocator():
  first_name_input = 'input[name="firstName"]'
  last_name_input='input[name="lastName"]'
  email_input='input[name="email"]'
  password_input='input[name="password"]'
  role_select = 'select[name="role"]'
  role_user_text = 'user'
  role_admin_text = 'admin'
  submit_created='#submitCreateNewUser'
  confirm_delete_user = '#submitDeleteUser'
